name: Build XCFramework
on:
  push

jobs:
  build:
    name: Build XCFramework
    runs-on: macos-latest
    env:
      DEVELOPER_DIR: /Applications/Xcode_14.1.app
    outputs:
      checksum: ${{ steps.checksum.outputs.checksum }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '1.19'
      - name: Build XCFramework
        run: |
          make zip
      - name: Compute checksum
        id: checksum
        run: |
          echo "checksum=$(swift package compute-checksum Frameworks/GOJQBinding.xcframework.zip)" >> $GITHUB_OUTPUT
      # - name: Release
      #   uses: softprops/action-gh-release@v1
      #   with:
      #     prerelease: true
      #     body: |
      #       Checksum: ${{ steps.checksum.outputs.checksum }}
      #     files: Frameworks/GOJQBinding.xcframework.zip
      #   if: startsWith(github.ref, 'refs/tags/')
